# Generated by Django 3.0.7 on 2020-06-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.BaseModel')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('post', models.TextField()),
                ('user', models.CharField(max_length=80)),
                ('comments', models.PositiveIntegerField()),
            ],
            bases=('backend.basemodel',),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.BaseModel')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
            bases=('backend.basemodel',),
        ),
    ]
